### ISSUE TITLE
Can the "User" be another system or an application?

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/reference-architecture#4]
**Description:**
In the first section, the "user" is defined as a human interacting with the system. But in enterprise systems, there can be B2B interactions where an application or a system can interact with the system.

**Comment by asankaa** [comment]
User is a human in this context who will be interacting with Channel Cells which represents end-user applications. 
Applications and systems are valid consumers, event-sync, and event-sources in CBA. However, those applications/systems represent as a Cell (channel/external/legacy) in CBA.
