### ISSUE TITLE
Are there any best practices for identifying the boundary of a cell?

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/reference-architecture#5]
**Description:**
Based on this architecture, defining the boundary of a cell is really challenging given the broader scope of a cell. It would be great to provide some best practices on defining the cell boundaries.

**Comment by asankaa** [comment]
Cell granularity/boundary is addressing in the next version of the specification (Q2-2019), WIP can find from the branch https://github.com/wso2/reference-architecture/blob/Q2-2019/reference-architecture-cell-based.md.
